language: go
sudo: required
services:
  - docker

go:
  - 1.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvips-dev

script:
  - go get -t ./...
  - FILE_LOCATION="./test" make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make docker;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lileio/image_service;
    fi
